import type { NextPage } from "next";
import Head from "next/head";
import ToDoContainer from "../components/ToDoContainer";

const Home: NextPage = () => {
  return (
    <div
      style={{
        background: "linear-gradient(0.125turn, #e66465, #9198e5)",
        minHeight: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Head>
        <title>To do</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToDoContainer />
    </div>
  );
};

export default Home;
